### ISSUE TITLE
wendy pipeline list shows null

### ISSUE THREAD

**Issue by TimoKramer** [bob-cd/wendy#10]
wendy pipeline list returns always null although there is correct output in bob-logs.

confirm:
`wendy pipeline create -c docs/build.toml`
`wendy pipeline list`

should be a list of the registered pipelines

actually null is returned in any case

**Comment by TimoKramer** [comment]
Is it not supposed to show pipelines independently of its status? I would assume to run `wendy pipeline list' and get a list of all pipelines...

**Comment by lispyclouds** [comment]
Yes we can do it like docker image list? Default all, and specify some optional `-f or --filter status:running` ?

**Comment by TimoKramer** [comment]
functionality is like expected but I opened https://github.com/bob-cd/bob/issues/75 to think about a better endpoint and then adapting wendy after it.
