### ISSUE TITLE
Cache cli-matic config locally

### ISSUE THREAD

**Issue by TimoKramer** [bob-cd/wendy#19]
The config is transformed from the api.yaml every time it is invoked. That means there is an HTTP-request to Bob and a transformation of the yaml to cli-matic-config every time. Using a `~/.wendy.edn` for storing the cli-matic conf should be an option.

Question is when will the cached config be renewed?

**Comment by lispyclouds** [comment]
This is now implemented by saving the YAML to `~/.bob.api.yaml` for subsequent calls. Also a new command `purge-cache` is available to force a re-fetch.
