### ISSUE TITLE
inconsistent cli params

### ISSUE THREAD

**Issue by TimoKramer** [bob-cd/wendy#8]
the cli params to list registered artifact-stores and external-resources are inconsistent:
```
root@bob-test:~/wendy# ./wendy artifact-store list
usage: wendy artifact-store [-h] COMMANDS ...
wendy: error: invalid choice: 'list' (choose from 'register', 'show', 'delete')

Did you mean:
        register
        show
```
```
root@bob-test:~/wendy# ./wendy external-resource show
usage: wendy external-resource [-h] COMMANDS ...
wendy: error: invalid choice: 'show' (choose from 'register', 'list', 'delete')
```

I think it should be list for returning a list of the registered systems and show for detailed view on a single system.

**Comment by TimoKramer** [comment]
commands.md says `external-resource ls` but it actually is `external-resource list`

**Comment by TimoKramer** [comment]
I'd prefer to use list for listing all the external-resources/artifact-stores and show for showing details of a single resource/store. So I will change `artifact-store list` to `artifact-store show` and change the commands.md accordingly

**Comment by lispyclouds** [comment]
fine by me. could you also update the deps https://versions.deps.co/bob-cd/wendy while you're at it? 😃

**Comment by TimoKramer** [comment]
Now I get why it says show. because you would think one only needs one artifact-store. still I prefer consistency and you never know...

UPDATE: typo
